import type { Bill } from "./columns";

export async function getBillData(): Promise<Bill[]> {
  return [
    {
      id: "bill-001",
      date: "2024-03-15",
      user: "张三",
      community: "阳光花园",
      unit: "1单元101",
      receivable: 12580,
      received: 10000,
      materials: [
        {
          id: "m1",
          materialId: "mat-001",
          name: "水泥",
          unit: "袋",
          quantity: 10,
          unitPrice: 45,
        },
        {
          id: "m2",
          materialId: "mat-002",
          name: "瓷砖",
          unit: "㎡",
          quantity: 120,
          unitPrice: 38,
        },
        {
          id: "m3",
          materialId: "mat-003",
          name: "防水涂料",
          unit: "桶",
          quantity: 5,
          unitPrice: 168,
        },
      ],
    },
    {
      id: "bill-002",
      date: "2024-03-18",
      user: "李四",
      community: "翠湖名苑",
      unit: "3单元205",
      receivable: 8600,
      received: 8600,
      materials: [
        {
          id: "m4",
          materialId: "mat-004",
          name: "电线",
          unit: "米",
          quantity: 200,
          unitPrice: 3.5,
        },
        {
          id: "m5",
          materialId: "mat-005",
          name: "开关插座",
          unit: "个",
          quantity: 24,
          unitPrice: 28,
        },
      ],
    },
    {
      id: "bill-003",
      date: "2024-04-02",
      user: "王芳",
      community: "阳光花园",
      unit: "2单元302",
      receivable: 5200,
      received: 3000,
      materials: [
        {
          id: "m6",
          materialId: "mat-006",
          name: "乳胶漆",
          unit: "桶",
          quantity: 8,
          unitPrice: 320,
        },
        {
          id: "m7",
          name: "腻子粉",
          unit: "袋",
          quantity: 15,
          unitPrice: 42,
        },
      ],
    },
    {
      id: "bill-004",
      date: "2024-04-10",
      user: "赵六",
      community: "锦绣家园",
      unit: "5单元101",
      receivable: 15800,
      received: 0,
      materials: [
        {
          id: "m8",
          materialId: "mat-007",
          name: "铝合金门窗",
          unit: "樘",
          quantity: 4,
          unitPrice: 1200,
        },
        { id: "m9", name: "玻璃", unit: "㎡", quantity: 6, unitPrice: 180 },
        { id: "m10", name: "密封胶", unit: "支", quantity: 12, unitPrice: 25 },
      ],
    },
    {
      id: "bill-005",
      date: "2024-04-22",
      user: "陈明",
      community: "翠湖名苑",
      unit: "1单元101",
      receivable: 3200,
      received: 3200,
      materials: [],
    },
  ];
}
